# Тема “Вычисления с помощью Numpy”

## Задание 1нта.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк
и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6,
8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива
Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [130]:
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [68]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
print(a)
print("Размерность А: {}".format(a.ndim))
print("Форма А: {}".format(a.shape))

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Размерность А: 2
Форма А: (5, 2)


In [70]:
mean_a = a.mean(axis=0)

mean_a

array([2. , 8.4])

## Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения
соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно
производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [72]:
a_centered = a - mean_a

a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [74]:
a_centered=np.subtract(a, mean_a)

a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна
получиться величина _centered_spa. Затем поделите a_centered_sp на N-1, где N - число
наблюдений.

In [80]:
a1=a_centered[:,0]
a2=a_centered[:,1]
a_centered_sp=np.dot(a1,a2)
a_centered_sp
N=a.shape[0]
my_cov=a_centered_sp/(N-1)
my_cov

2.0

## Задание 4**

In [92]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

# Тема “Работа с данными в Pandas”

## Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со
столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и
['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно
содержатся данные:
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники']
Нужны prices!
[500, 400, 300, 350, 450, 600, 200]

In [108]:
import pandas as pd

In [110]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                   'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [112]:
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     'price':[500, 400, 300, 350, 450, 600, 200]}, 
                      columns=['author_id', 'book_title', 'price'])
books

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

# Задан

Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

In [118]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

# Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими
книгами.

In [120]:
top5=authors_price.nlargest(5, 'price')
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

# Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat
должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя
цена на книги этого автора.

In [122]:
df1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})
df3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
authors_stat=pd.concat([df1, df2, df3], axis = 1)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         200        600       400.0
Тургенев           300        500       400.0
Чехов              350        450       400.0

# Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться
данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные
из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте
для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а
индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,
при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием
"book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь,
что датафреймы book_info и book_info2 идентичны.

In [124]:
df1 = pd.DataFrame({'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']}, columns=['cover'])
authors_price = pd.concat([authors_price, df1], axis = 1)
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    500  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    300   мягкая
3          2       Чехов      Толстый и тонкий    350  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    600   мягкая
6          3  Островский  Таланты и поклонники    200   мягкая

In [126]:
?pd.pivot_table

Signature:
pd.pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins: 'bool' = False,
    dropna: 'bool' = True,
    margins_name: 'Hashable' = 'All',
    observed: 'bool' = False,
    sort: 'bool' = True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : list-like or scalar, optional
    Column or columns to aggregate.
index : column, Grouper, array, or list of the previous
    Keys to group by on the pivot table index. If a list is passed,
    it can contain any of the other types (except list). If an array is
    passed, it must be the same length as the data and will be used in
    the same manner as column values.
columns : column, Grouper, array, or list of the

In [132]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
                    columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800

In [136]:
book_info.to_pickle('book_info.pkl')

In [138]:
book_info2 = pd.read_pickle('book_info.pkl')

In [140]:
book_info==book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True